[package]
name = "suisoul"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
# Sui Framework bağımlılığını ekliyoruz. 
# Eğer localde çalışıyorsan local path verebilirsin ama genelde git üzerinden çekilir.
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
suisoul = "0x0" 

[dev-dependencies]
# Testler için gerekli olabilir, şimdilik boş kalabilir veya yorum satırı olabilir.